### ISSUE TITLE
Can you explain how to us ? thx

### ISSUE THREAD

**Issue by issour** [zareismail/nova-wizard#1]

**Comment by zareismail** [comment]
> _No description provided._

Hi. this package is not completed.
But there is an interface `Zareismail\Nova Wizard\Contracts\Wizard` that your resource should implement that it. then there exists `Step` field for each `Step` like a `Panel`.

simple example:

```
class MyResource extends Resource implements Wizard 
{
      function fields()
      {
           new Step('One', [
                        // some fields
           ])
      } 
}
````

Thanks and Greet if report bugs

**Comment by issour** [comment]
hi @zareismail thx you !! 
i will report if any bug or suggestion :)

**Comment by zareismail** [comment]
Hi. use release 0.1.0
