### ISSUE TITLE
Wizard acro multiple resources?

### ISSUE THREAD

**Issue by cord** [zareismail/nova-wizard#3]
Can a wizard cover a flow across multiple resources? If yes an example would be great!

**Comment by zareismail** [comment]
can you explain what do you want via an example?

**Comment by cord** [comment]
Am thinking of something like the following:

there are 3 resources:
- customer
- customer_address
- customer_group

a customer has one or more adress-items
a customer belongs to one or more customer groups

So the wizard would look like this:

step 1: enter customer details (name, email address)
step 2: enter customer address (creates and attaches)
step 3: assign the customer to one or more customer groups (attaches)

would this setup be possible?

**Comment by zareismail** [comment]
hi. 
you can implement this by `fillUsing` callbacks.
For that, you could use the `checkpoint` on the first step and store your customer in DB

**Comment by cord** [comment]
Nice! An example would be great!
