### ISSUE TITLE
[BUG] When you close the wizard, the session isn't cleared

### ISSUE THREAD

**Issue by ThaDaVos** [zareismail/nova-wizard#7]
When the wizard is closed, the current object is not cleared from the session, so if you cancel it and then open the wizard again, it starts at a the step you were at (except if it's the last, then it starts at the previous step).

**Comment by ThaDaVos** [comment]
I forked your project, so I may submit a pull-request later :D

**Comment by ThaDaVos** [comment]
https://github.com/zareismail/nova-wizard/pull/8

**Comment by zareismail** [comment]
#8
